{% set name = "sktime" %}
{% set version = "0.24.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d5ac84546676fd64fb05bb5fc077d38703bea3bcf711885e992da7bf12f6b83

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy <1.27,>=1.21
    - packaging
    - pandas >=1.1,<2.2.0
    - skbase <0.7.0
    - scikit-learn >=0.24,<1.4.0
    - scipy >=1.2.0,<2.0.0
  run_constrained:
    - arch >=5.6,<6.3.0
    - cloudpickle
    - dask
    - dtw-python
    - esig 0.9.7  # [py<10]
    - filterpy >=1.4.5  # [py<311]
    - gluonts >=0.9
    - h5py  # [py<312]
    - hmmlearn  # [py<311]
    - holidays
    - keras-self-attention  # [py<311]
    - kotsu >=0.3.1
    - matplotlib-base >=3.3.2
    - mne
    - numba >=0.53,<0.59
    - pmdarima >1.8.1,<3.0.0  # [py<312]
    - prophet >=1.1  # [py<312]
    - pykalman-bardo >=0.9.7,<0.10
    - pyod >=0.8  # [py<312]
    - scikit-optimize
    - seaborn >=0.11
    - seasonal
    - skpro >=2,<2.2.0
    - statsforecast <1.7.0,>=0.5.2  # [py<312]
    - statsmodels >=0.12.1
    - stumpy >=1.5.1  # [py<311]
    - tbats >=1.1  # [py<312]
    - tensorflow  # [py<312]
    - tsfresh >=0.17  # [py<312]
    - tslearn >=0.5.2,<0.6.0  # [py<311]
    - xarray

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - sktime
    - sktime.classification
    - sktime.datasets
    - sktime.distances
    - sktime.forecasting
    - sktime.performance_metrics
    - sktime.regression
    - sktime.series_as_features
    - sktime.transformations
    - sktime.utils


about:
  home: https://github.com/sktime/sktime
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A unified framework for machine learning with time series
  description: A unified framework for machine learning with time series
  doc_url: https://www.sktime.net/en/latest/
  dev_url: https://github.com/sktime/sktime

extra:
  recipe-maintainers:
    - yarnabrina
    - fkiraly
    - dhirschfeld
    - freddyaboulton
