{% set name = "sktime" %}
{% set version = "0.17.0" %}

package:
  name: sktime-suite
  version: {{ version }}

source:
  url: https://github.com/sktime/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 75cb18dbc2fc4e15316130e1401e676f568faade8b711b5140e8c2fd1ff60b06

build:
  number: 0
  # numba is not available on s390x
  skip: true  # [s390x]
  skip: true  # [py<37 or py>311]

# This section is required to correctly rerender skip statement
requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - toml
    - python-build

outputs:
  - name: sktime
    script: build_script.sh  # [unix]
    script: build_script.bat  # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
        - toml
        - python-build
      run:
        - python
        - deprecated >=1.2.13
        - numba>=0.53
        - numpy >=1.21.0,<1.25
        - pandas >=1.1.0,<2.0.0
        - scikit-learn >=0.24.0,<1.3.0
        - scipy >=1.2.0,<2.0.0
      run_constrained:
        - esig ==0.9.7
        - filterpy >=1.4.5
        - gluonts >=0.9.0
        - hmmlearn >=0.2.7
        - kotsu >=0.3.1
        - matplotlib-base >=3.3.2
        - pmdarima >=1.8.0,!=1.8.1,<3.0.0
        - prophet >=1.1
        - pykalman >=0.9.5
        - pyod >=0.8.0
        - pystan ==2.19.1.1
        - scikit-posthocs >=0.6.5
        - seaborn >=0.11.0
        - statsforecast >=0.5.2
        - statsmodels >=0.12.1
        - stumpy >=1.5.1
        - tbats >=1.1.0
        - tsfresh >=0.17.0
        - tslearn >=0.5.2
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

  - name: sktime-all-extras
    build:
      # Skip building this package because many of the dependencies are not available yet.
      skip: true
    requirements:
      run:
        - python
        - {{ pin_subpackage("sktime", max_pin='x.x.x') }}
        - attrs
        - cloudpickle
        - dask
        - dtw-python
        # - esig  # not on CF
        - filterpy
        - h5py
        # - hmmlearn  # not on CF
        - gluonts
        - matplotlib-base
        - mne
        - numba >=0.53
        - pmdarima
        - prophet
        - pykalman
        - pyod
        - scikit-posthocs
        - seaborn
        # - seasonal  # not on CF
        - statsforecast
        - stumpy
        - tbats
        - tsfresh
        - tslearn
        - xarray

    test:
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

about:
  home: https://github.com/sktime/sktime
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A unified framework for machine learning with time series
  description: A unified framework for machine learning with time series
  doc_url: https://www.sktime.net/en/latest/
  dev_url: https://github.com/sktime/sktime

extra:
  recipe-maintainers:
    - yarnabrina
    - fkiraly
    - dhirschfeld
    - freddyaboulton
